name: Get PR Commit Files
on:
  pull_request:
    types:
      - synchronize

jobs:
  get_files:
    runs-on: ubuntu-latest
    container:
     image: magento/magento-cloud-docker-php:8.1-fpm-1.3.2
    steps:
      - name: Installing git and curl
        run: |    
          apt-get update && apt-get install -y unzip git
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Get PR commit files
        id: pr_files
        run: |
          PR_NUMBER=$(echo "${{ github.event.pull_request.url }}" | awk -F'/' '{print $NF}')
          PR_FILES=$(curl -sSL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                      -H "Accept: application/vnd.github.v3+json" \
                      "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/files" \
                      | jq -r '.[].filename')
          echo "::set-output name=files::${PR_FILES}"

      - name: Print PR commit files
        run: |
          echo "Files modified in PR commit:"
          echo "${{ steps.pr_files.outputs.files }}"
      - name: Install composer dependencies
        run: |
         curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
         composer self-update -- 2.1.1
         composer install --ignore-platform-req=ext-sodium
      - name: Run Testsuite
        run: |
          vendor/bin/phpcs -i
